#ifndef COMMAND_H_Record_and_Replay
#define COMMAND_H_Record_and_Replay

#include <linux/ioctl.h>
#define RECORDANDREPLAY			0xaa
#define IOCTL_RESET				_IO(RECORDANDREPLAY, 0)
#define IOCTL_SET_PID_RECORD	_IOW(RECORDANDREPLAY, 1, int)
#define IOCTL_GET_PID_RECORD	_IOR(RECORDANDREPLAY, 2, int)
#define IOCTL_START_RECORD		_IO(RECORDANDREPLAY, 3)
#define IOCTL_STOP_RECORD		_IO(RECORDANDREPLAY, 4)
#define IOCTL_START_REPLAY		_IO(RECORDANDREPLAY, 5)
#define IOCTL_STOP_REPLAY		_IO(RECORDANDREPLAY, 6)
#define IOCTL_SET_PID_REPLAY	_IOW(RECORDANDREPLAY, 7, int)
#define IOCTL_GET_PID_REPLAY	_IOR(RECORDANDREPLAY, 8, int)
#endif
